"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { getAllProducts, refreshToken } from "./helpers/axios/axios";
import { useStore } from "./page";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { ProductProps } from "./helpers/Interfaces/Interfaces";
import SlidingCart from "./components/SlidingCart/SlidingCart";
import Container from "./components/Container/Container";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthed, isDark } = useStore();
  const [products, setProducts] = useState<ProductProps[]>([]);

  const fetchAllProducts = async () => {
    try {
      const productsData = await getAllProducts();
      setProducts(productsData);
    } catch (error: any) {
      console.error("Error fetching categories: ", error);
    }
  };

  useEffect(() => {
    refreshToken();
    fetchAllProducts();
    const intervalId = setInterval(() => {
      refreshToken();
    }, 5 * 60 * 1000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${
          isDark ? `bg-[#252424] text-white` : `bg-[#f1f3f6] text-black`
        } `}
      >
        <Container>
          <Header products={products} />
          <SlidingCart />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
